apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripsviewer
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripsviewer
  template:
    metadata:
      labels:
        app: tripsviewer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tripsviewer
        image: registryqhy3162.azurecr.io/tripinsights/tripviewer:v2
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://tripsapp.api"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.api"
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: tripsviewer
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripsviewer