apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripsapp
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripsapp
  template:
    metadata:
      labels:
        app: tripsapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tripsapp
        image: registryqhy3162.azurecr.io/tripinsights/trips:v1
        # env:
        # - name: SQL_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: joao-test-secret
        #       key: username
        # - name: SQL_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: joao-test-secret
        #       key: password
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: tripsapp
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: tripsapp