kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-full-access-role
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-access-rolebinding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-user-full-access-role
subjects:
- kind: Group
  namespace: web
  name: "6bc6d65e-2353-41f8-93cb-2716ec4647dd"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-full-access-role
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-access-rolebinding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-user-full-access-role
subjects:
- kind: Group
  namespace: api
  name: "6bc6d65e-2353-41f8-93cb-2716ec4647dd"