# This is a SecretProviderClass example using user-assigned identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: joao-azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  # secretObjects:
  # - secretName: test-secret
  #   type: Opaque
  #   data:
  #   - objectName: SQLServerUsername
  #     key: dbuser
  #   - objectName: SQLServerPassword
  #     key: dbpassword
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 255c1831-e271-4175-a28b-579f1113c860   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: OpenKAckVault        # Set to the name of your Azure Key Vault instance
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLServerUsername
          objectAlias: SQL_USER        
          objectType: secret            # object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLServerPassword
          objectAlias: SQL_PASSWORD
          objectType: secret              # object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 1c054575-7f2d-4829-92ff-f2bcbc899e66                 # The tenant ID of the Azure Key Vault instance